### ISSUE TITLE
Developer setup on macos

### ISSUE THREAD

**Issue by MartinDelille** [PierreBresson/Thinkerview#35]
Hi @PierreBresson and thank you for sharing the code for the Thinkerview app!

I have some issue on iOS 13.3.1 on my iPhone SE and wanted to debug it myself.

I will post some issue and would be happy if you have some clue on how to fix them.

I'm totally noob in react (I personally prefer using real native framework like https://www.qt.io/) but I might learn fast because I have already some VueJS and Angular basis.

I ran `yarn` and if it displayed a lot of warnings it dit succeed (despite it removed the `react-native-background-downloader@2.0.1` dependency from `yarn.lock`.

Unfortunately I'm now stuck when starting the following command:

```
react-native run-ios
info Found Xcode project thinkerview.xcodeproj
CoreData: annotation:  Failed to load optimized model at path '/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Frameworks/InstrumentsPackaging.framework/Versions/A/Resources/XRPackageModel.momd/XRPackageModel 9.0.omo'
error Could not find iPhone X simulator
```

**Comment by PierreBresson** [comment]
Hello @MartinDelille 
Thanks for the help!
Indeed, you will learn fast if you know angular/vue/
Can you start both xcode and simulator app without Thinkerview. Like create a new blank project to see if everything works. You might have to download some dev tools and agree to apple licences before being able to run anything.
